TrajectoryPlannerROS:
  acc_lim_theta: 1.5
  acc_lim_x: 2.00
  acc_lim_y: 0.0

  max_vel_x: 0.8
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.15
  escape_vel: -0.15

  holonomic_robot: false

  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: true

  sim_time: 1.4
  sim_granularity: 0.025
  angular_sim_granularity: 0.05
  vx_samples: 5
  vy_samples: 0
  vtheta_samples: 20

  meter_scoring: true

  pdist_scale:  0.6
  gdist_scale: 0.5
  occdist_scale: 0.05

  dwa: true

  heading_lookahead: 0.55
  heading_scoring: false
  heading_scoring_timestep: 0.8
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.10
  
  publish_cost_grid_pc: true

controller_frequency: 10.00

