obstacle_range: 2.5
raytrace_range: 5.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
footprint: [[-0.55, -0.035], [-0.13, -0.33], [0.15, -0.33], [0.38, -0.11], [0.38, 0.11], [0.15, 0.33], [-0.13, 0.33], [-0.55, 0.035]]
footprint_padding: 0.01
#robot_radius: 0.45
inflation_radius: 0.20
cost_scaling_factor: 100.0
#transform_tolerance: 1.20
observation_sources: IS16_sensor hokuyo_sensor

IS16_sensor: {sensor_frame: IS16_link, data_type: LaserScan, topic: /scan/leddar_scan, marking: true, clearing: true}

hokuyo_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /scan/hokuyo_scan, marking: true, clearing: true}

